Repository italo-mauricio/App-Brasileirao, pull requests merged in 2023-06, with the labels that each got.

#26 Feat/issue#25
  brasileirao/lib/utils/Controller.dart
  brasileirao/lib/utils/keysAuth.dart
Labels: enhancement

#28 Feat/issue#12
  brasileirao/lib/home/HomePage.dart
  brasileirao/lib/sections/Matches.dart
  brasileirao/lib/utils/Controller.dart
  brasileirao/lib/utils/keysAuth.dart
Labels: enhancement

#29 feat: init create table path
  brasileirao/lib/components/Drawer.dart
  brasileirao/lib/components/NavigationBar.dart
  brasileirao/lib/home/HomePage.dart
  brasileirao/lib/routes/InitialApp.dart
  brasileirao/lib/sections/Table.dart
  brasileirao/lib/utils/Controller.dart
Labels: enhancement

#38 Italo
  brasileirao/android/build.gradle
  brasileirao/lib/components/Drawer.dart
  brasileirao/lib/controllers/BrasileiraoController.dart
  brasileirao/lib/home/HomePage.dart
  brasileirao/lib/sections/ChaviamentoCopa.dart
  brasileirao/lib/sections/FaseCopaBrasil.dart
  brasileirao/lib/sections/Table.dart
  brasileirao/lib/utils/keysAuth.dart
Labels: enhancement

#40 Feat/issue#12
  brasileirao/lib/controllers/BrasileiraoController.dart
  brasileirao/lib/home/HomePage.dart
  brasileirao/lib/sections/DescriptionsMatches.dart
  brasileirao/lib/sections/Matches.dart
Labels: bug, enhancement

#42 Implementando Estrutura do projeto e alterações
  README.md
  brasileirao/README.md
  brasileirao/lib/utils/keysAuth.dart
Labels: documentation

#43 Feat/issue#35
  brasileirao/lib/controllers/BrasileiraoController.dart
  brasileirao/lib/home/HomePage.dart
  brasileirao/lib/sections/ChaviamentoCopa.dart
Labels: enhancement

#45 Limitando acesso a busca por rodadas
  brasileirao/lib/controllers/BrasileiraoController.dart
Labels: bug, enhancement
